@startuml envio-informe

title Diagrama de Secuencia para el Informe Resultante de Anatomía Patológica

hide footbox

!include ./style.iuml

actor "Anatopatólogo" as usuario
participant "Sistema Informático de Anatomía Patológica" as PAIS
database "Repositorio Anatomías Patológicas" as RepositorioBiopsia

usuario -> PAIS: Genera informe de anatomía patológica
activate PAIS
PAIS -> PAIS: Genera informe en estructura FHIR (xml o json)
PAIS -> RepositorioBiopsia: Solicitud de Token de Autenticación
activate RepositorioBiopsia
alt Token válido
    RepositorioBiopsia -> PAIS: Respuesta con Token de Autenticación
    PAIS -> RepositorioBiopsia: Realiza un POST a la API FHIR
    RepositorioBiopsia -> RepositorioBiopsia: Valida formato del FHIR
    alt Formato válido
        RepositorioBiopsia -> RepositorioBiopsia: Actualiza solicitud de informe
        RepositorioBiopsia -> RepositorioBiopsia: Almacena el informe en la base de datos 
        RepositorioBiopsia -> PAIS: Respuesta exitosa (201 Created)
    else Formato inválido
        RepositorioBiopsia -> PAIS: Respuesta de error (400 Bad Request)
    end
else Token inválido
    RepositorioBiopsia -> PAIS: Respuesta de error (401 Unauthorized)
    deactivate RepositorioBiopsia
end 
PAIS -> usuario: Notifica el estado del informe en el repositorio
deactivate PAIS

@enduml