@startuml Diagrama de Secuencia para la Solicitud de Informe de Anatomía Patológica

title Diagrama de Secuencia para la Solicitud de Informe de Anatomía Patológica

hide footbox
!include ./style.iuml

actor usuario
participant "Sistema Informático Externo" as Aplicativo
database "Repositorio Anatomías Patológicas" as RepositorioBiopsia

usuario -> Aplicativo: Genera solicitud de informe de anatomía patológica
activate Aplicativo
Aplicativo -> Aplicativo: Genera solicitud en estructura FHIR (xml o json)
Aplicativo -> RepositorioBiopsia: Realiza un POST a la API FHIR
activate RepositorioBiopsia
RepositorioBiopsia -> RepositorioBiopsia: Valida formato del FHIR
alt Formato válido
    RepositorioBiopsia -> RepositorioBiopsia: Almacena el solicitud en la base de datos
    RepositorioBiopsia -> Aplicativo: Respuesta exitosa (201 Created)
else Formato inválido
    RepositorioBiopsia -> Aplicativo: Respuesta de error (400 Bad Request)
end
deactivate RepositorioBiopsia
Aplicativo -> usuario: Notifica el estado de la solicitud
deactivate Aplicativo

@enduml