@startuml Iteracciones con Servidor Terminológico

actor Usuario
participant Aplicativo
database "Servidor Terminológico" as ST

Usuario -> Aplicativo: Escribe Termino
Aplicativo -> ST: Obtención de Token
ST -> Aplicativo: Token
Aplicativo -> ST: Consulta mediante operación $expand
ST -> Aplicativo: Respuesta de Códigos Snomed CT
Aplicativo -> Usuario: Muestra Terminos Snomed CT
Usuario -> Aplicativo: Selecciona Termino
Aplicativo -> ST: Realiza operacion $translate
ST -> Aplicativo: Respuesta de Código CIE-10 o CIE-O
Aplicativo -> Aplicativo: Carga códigos Snomed CT más CIE-10 o CIE-O en recurso FHIR

@enduml